<?php

namespace Database\Seeders;

use App\Models\User;
use BezhanSalleh\FilamentShield\Support\Utils;
use Filament\Facades\Filament;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;
use Spatie\Permission\Models\Role;

class RolesAndPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        Filament::setCurrentPanel(Filament::getPanel('admin'));

        Artisan::call('shield:generate', [
            '--all' => true,
            '--option' => 'policies_and_permissions',
            '--panel' => 'admin',
        ]);

        // Custom page-level permissions (not auto-generated by shield)
        $customPerms = ['view_dashboard', 'view_studies'];
        $permModel = Utils::getPermissionModel();
        foreach ($customPerms as $name) {
            $permModel::firstOrCreate(['name' => $name, 'guard_name' => 'web']);
        }

        // super_admin — all permissions
        $super = Utils::createRole();
        $super->syncPermissions(Utils::getPermissionModel()::pluck('id'));

        // Custom roles with scoped permissions
        $this->createRole('radiologist', [
            'ViewAny:Order', 'View:Order',
            'ViewAny:Patient', 'View:Patient',
            'ViewAny:WorklistItem', 'View:WorklistItem',
            'ViewAny:Report', 'Create:Report', 'View:Report', 'Update:Report',
            'view_dashboard', 'view_studies',
        ]);

        $this->createRole('radiographer', [
            'ViewAny:Order', 'View:Order',
            'ViewAny:Patient', 'View:Patient',
            'ViewAny:WorklistItem', 'Create:WorklistItem', 'View:WorklistItem', 'Update:WorklistItem',
            'view_dashboard', 'view_studies',
        ]);

        $this->createRole('dokter', [
            'ViewAny:Order', 'View:Order',
            'ViewAny:Patient', 'View:Patient',
            'ViewAny:Report', 'View:Report',
            'view_dashboard',
        ]);

        // Assign super_admin to admin user
        $user = User::where('email', 'admin@admin.com')->first();
        if ($user) {
            $user->assignRole($super);
        }
    }

    protected function createRole(string $name, array $permissions): Role
    {
        $role = Role::findOrCreate($name, 'web');
        $role->syncPermissions($permissions);

        return $role;
    }
}
